# Generated by Django 3.0.7 on 2020-06-10 09:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodBase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=70)),
                ('description', models.TextField(blank=True, max_length=200)),
                ('energy', models.PositiveSmallIntegerField()),
                ('fat_total', models.DecimalField(decimal_places=2, max_digits=4)),
                ('fat_saturated', models.DecimalField(decimal_places=2, max_digits=4)),
                ('carb_total', models.DecimalField(decimal_places=2, max_digits=4)),
                ('carb_sugar', models.DecimalField(decimal_places=2, max_digits=4)),
                ('fibre', models.DecimalField(decimal_places=2, max_digits=4)),
                ('protein', models.DecimalField(decimal_places=2, max_digits=4)),
                ('salt', models.DecimalField(decimal_places=2, max_digits=4)),
                ('tags', models.TextField(blank=True)),
                ('brand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='food.Brand')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
