# Generated by Django 3.0.7 on 2020-06-10 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_foodbase'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodbase',
            name='carb_non_sugar',
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='foodbase',
            name='fat_unsaturated',
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='foodbase',
            name='carb_sugar',
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='foodbase',
            name='carb_total',
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='foodbase',
            name='energy',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='foodbase',
            name='fat_saturated',
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='foodbase',
            name='fat_total',
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='foodbase',
            name='fibre',
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='foodbase',
            name='protein',
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='foodbase',
            name='salt',
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True),
        ),
    ]
