# Generated by Django 3.0.7 on 2020-06-10 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_auto_20200610_1111'),
    ]

    operations = [
        migrations.RenameField(
            model_name='foodbase',
            old_name='salt',
            new_name='salt_amount',
        ),
    ]
