# Generated by Django 3.0.7 on 2020-06-10 13:30

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0004_auto_20200610_1255'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.FoodBase')),
            ],
        ),
    ]
